name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        webrpc-gen: [v0.7.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install webrpc-gen
        #run: go install github.com/webrpc/webrpc/cmd/webrpc-gen@${{ matrix.webrpc-gen }}
        run: git clone --single-branch https://github.com/webrpc/webrpc.git --branch master && cd webrpc && make install
      - name: Regenerate example schema
        run: cd _examples && make generate
      - name: Git diff of regenerated files
        run: cd _examples && make diff
